spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}
    requested-heartbeat: 60
    listener:
      simple:
        missing-queues-fatal: false

  cloud:
    bus:
      enabled: true
      id: ${spring.application.name}:${server.port}
      refresh:
        enabled: true
      env:
        enabled: true
    stream:
      bindings:
        springCloudBusInput:
          group: ${spring.application.name}-${server.port}
      rabbit:
        bindings:
          springCloudBusInput:
            consumer:
              missing-queues-fatal: false
              recovery-interval: 5000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
