server:
  port: 8083

openapi:
  title: Order Service API
  description: REST API for cart and order management.
  version: 1.0.0
  server-url: /

clients:
  user-service:
    url: http://localhost:8081
  product-service:
    url: http://localhost:8082

rabbitmq:
  exchange:
    name: order.exchange
  queue:
    name: order.queue
  routing:
    key: order.tracking

spring:
  rabbitmq:
    host: ${RABBIT_HOST:rabbitmq}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}
    requested-heartbeat: 60
    listener:
      simple:
        missing-queues-fatal: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/userdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  ratelimiter:
    instances:
      rateBreaker:
        limitForPeriod: 3
        limitRefreshPeriod: 5s
        timeoutDuration: 0
        registerHealthIndicator: true
