server:
  port: 8888

spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    refresh:
      never-refreshable: org.springframework.cloud.config.server.config.ConfigServerHealthIndicator
    config:
      server:
        native:
          search-locations: ${CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS:classpath:/config/,file:/config/}
    bus:
      enabled: true
      id: ${spring.application.name}:${server.port}
    stream:
      bindings:
        springCloudBusInput:
          group: ${spring.application.name}-${server.port}
      rabbit:
        bindings:
          springCloudBusInput:
            consumer:
              missing-queues-fatal: false
              recovery-interval: 5000
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}
    requested-heartbeat: 60
    listener:
      simple:
        missing-queues-fatal: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
