spring.application.name=order-service
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
clients.user-service.url=http://localhost:8081
clients.product-service.url=http://localhost:8082
