spring.application.name=order-service
server.port=8083
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
clients.user-service.url=${USER_SERVICE_URL:http://localhost:8081}
clients.product-service.url=${PRODUCT_SERVICE_URL:http://localhost:8082}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/userdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
openapi.title=Order Service API
openapi.description=REST API for cart and order management.
openapi.version=1.0.0
openapi.server-url=/
rabbitmq.exchange.name=${RABBIT_EXCHANGE_NAME:order.exchange}
rabbitmq.queue.name=${RABBIT_QUEUE_NAME:order.queue}
rabbitmq.routing.key=${RABBIT_ROUTING_KEY:order.tracking}
spring.rabbitmq.host=${RABBIT_HOST:rabbitmq}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.username=${RABBIT_USER:guest}
spring.rabbitmq.password=${RABBIT_PASSWORD:guest}
spring.rabbitmq.listener.simple.missing-queues-fatal=false
